# Generated by Django 5.0.4 on 2024-05-02 13:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('authorization_code', models.CharField(max_length=4)),
                ('invite_code', models.CharField(max_length=6)),
            ],
        ),
    ]
