# Generated by Django 5.0.4 on 2024-05-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
