# Generated by Django 5.0.4 on 2024-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0003_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_jwt',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
