# Generated by Django 5.0.4 on 2024-05-08 09:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0005_userprofile_code_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code_used',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True),
        ),
    ]
