# Generated by Django 5.0.4 on 2024-05-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0006_remove_userprofile_code_used_userprofile_used_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='token_jwt',
            new_name='access_token',
        ),
    ]
