# Generated by Django 5.0.4 on 2024-05-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0007_rename_token_jwt_userprofile_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='authorization_code',
            new_name='authentication_code',
        ),
    ]
